export const GET_BOOKFORVIEWER_START = 'BOOK/GET_BOOKFORVIEWER_START';
export const GET_BOOKFORVIEWER_SUCCEED = 'BOOK/GET_BOOKFORVIEWER_SUCCEED';
export const GET_BOOKFORVIEWER_FAIL = 'BOOK/GET_BOOKFORVIEWER_FAIL';
