export const GET_BOOK_SENTENCE_LIST_START = 'BOOK/GET_BOOK_SENTENCE_LIST_START';
export const GET_BOOK_SENTENCE_LIST_SUCCEED =
  'BOOK/GET_BOOK_SENTENCE_LIST_SUCCEED';
export const GET_BOOK_SENTENCE_LIST_FAIL = 'BOOK/GET_BOOK_SENTENCE_LIST_FAIL';

export const POST_BOOK_SENTENCE_START = 'BOOK/POST_BOOK_SENTENCE_START';
