export const GET_BOOK_PAGE_START = 'BOOK/GET_BOOK_PAGE_START';
export const GET_BOOK_PAGE_SUCCEED = 'BOOK/GET_BOOK_PAGE_SUCCEED';
export const GET_BOOK_PAGE_FAIL = 'BOOK/GET_BOOK_PAGE_FAIL';

export const POST_BOOK_PAGE_START = 'BOOK/POST_BOOK_PAGE_START';
