export const GET_BOOK_QUESTION_LIST_START = 'BOOK/GET_BOOK_QUESTION_LIST_START';
export const GET_BOOK_QUESTION_LIST_SUCCEED =
  'BOOK/GET_BOOK_QUESTION_LIST_SUCCEED';
export const GET_BOOK_QUESTION_LIST_FAIL = 'BOOK/GET_BOOK_QUESTION_LIST_FAIL';
