export const GET_ANSWERS_FROM_AUTHOR_START =
  'BOOK/GET_ANSWERS_FROM_AUTHOR_START';
export const GET_ANSWERS_FROM_AUTHOR_SUCCEED =
  'BOOK/GET_ANSWERS_FROM_AUTHOR_SUCCEED';
export const GET_ANSWERS_FROM_AUTHOR_FAIL =
  'BOOK/GET_ANSWERS_FROM_AUTHOR_FAIL';
export const GET_ANSWERS_FROM_READER_START =
  'BOOK/GET_ANSWERS_FROM_READER_START';
export const GET_ANSWERS_FROM_READER_SUCCEED =
  'BOOK/GET_ANSWERS_FROM_READER_SUCCEED';
export const GET_ANSWERS_FROM_READER_FAIL =
  'BOOK/GET_ANSWERS_FROM_READER_FAIL';
