export const GET_DETAIL_QUESTIONS_START =
  'BOOK/GET_DETAIL_QUESTIONS_START';
export const GET_DETAIL_QUESTIONS_SUCCEED =
  'BOOK/GET_DETAIL_QUESTIONS_SUCCEED';
export const GET_DETAIL_QUESTIONS_FAIL =
  'BOOK/GET_DETAIL_QUESTIONS_FAIL';
